import React from 'react';
import Markdown from 'react-markdown';
import { ExternalLink, BookOpen, Share2 } from 'lucide-react';
import { motion } from 'motion/react';

interface Source {
  uri: string;
  title: string;
}

interface InsightDisplayProps {
  content: string;
  sources: Source[];
}

export const InsightDisplay: React.FC<InsightDisplayProps> = ({ content, sources }) => {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 w-full max-w-7xl mx-auto">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="lg:col-span-2 space-y-8"
      >
        <div className="glass-panel p-8 md:p-12">
          <div className="flex items-center justify-between mb-8 pb-4 border-bottom border-white/5">
            <div className="flex items-center gap-3 text-orange-400">
              <BookOpen size={20} />
              <span className="text-xs font-semibold uppercase tracking-[0.2em]">Synthesis Report</span>
            </div>
            <button className="text-white/40 hover:text-white transition-colors">
              <Share2 size={18} />
            </button>
          </div>
          
          <div className="markdown-body">
            <Markdown>{content}</Markdown>
          </div>
        </div>
      </motion.div>

      <motion.div 
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.2 }}
        className="space-y-6"
      >
        <div className="glass-panel p-6">
          <h3 className="text-xs font-semibold uppercase tracking-widest text-white/40 mb-6 flex items-center gap-2">
            <ExternalLink size={14} />
            Grounded Sources
          </h3>
          
          <div className="space-y-4">
            {sources.length > 0 ? (
              sources.map((source, i) => (
                <a
                  key={i}
                  href={source.uri}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="block p-4 rounded-2xl bg-white/[0.02] border border-white/5 hover:bg-white/[0.05] hover:border-white/10 transition-all group"
                >
                  <h4 className="text-sm font-medium text-white/80 group-hover:text-orange-400 transition-colors line-clamp-2 mb-2">
                    {source.title}
                  </h4>
                  <div className="flex items-center gap-2 text-[10px] text-white/30 truncate">
                    <span className="bg-white/5 px-2 py-0.5 rounded uppercase tracking-wider">Web</span>
                    <span className="truncate">{new URL(source.uri).hostname}</span>
                  </div>
                </a>
              ))
            ) : (
              <div className="py-8 text-center text-white/20 italic text-sm">
                No external sources grounded for this synthesis.
              </div>
            )}
          </div>
        </div>

        <div className="glass-panel p-6 bg-orange-500/5 border-orange-500/10">
          <h3 className="text-xs font-semibold uppercase tracking-widest text-orange-400/60 mb-3">Aura Intelligence</h3>
          <p className="text-xs text-white/50 leading-relaxed">
            This report was synthesized using Gemini 3.1 Pro with real-time web grounding. Insights are generated by connecting disparate data points into a cohesive narrative.
          </p>
        </div>
      </motion.div>
    </div>
  );
};
